services:
  baobaoge-backup:
    image: baibaoge-backup:latest
    container_name: baibaoge-backup
    ports:
      - "5050:5000"
    volumes:
      - /share/Container/baobaoge/backup:/backup
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
